name: CI/CD Workflow

on:
  push:
    branches:
      - main    # Trigger workflow on push to 'main' branch
  pull_request:
    branches:
      - main    # Trigger workflow on pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Use the required Python version

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov

    # Run tests
    - name: Run tests
      run: |
        pytest tests/ --cov=src